### PR TITLE
Customizable Navbar via site.config.js and props (Fixes #108)

### LINKED ISSUE #108: Default components cannot be customised
**Describe the bug**

The documentation advertises using built-in components such as `<NavigationBar>`, but those are hard-coded to e.g. rendering "StatueSSG" or links to an /about page. This makes these components pretty much unusable.

**Expected behavior**

Pull values such as the site title from the configuration, and most importantly allow overriding things using Snippets (or slots, if using legacy Svelte).

**To Reproduce**
1. Set up Statue according to the documentation
2. Open the page
3. See error

**Configuration**
Not applicable

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by semihpolat**
Summary
  - Made NavigationBar component fully customizable via site.config.js
  - Added siteTitle, logo, defaultNavItems, and ctaButton props
  - Removed hardcoded "StatueSSG" branding and "/about", "/docs" links
  - Updated blog template config with navbar section

  Fixes #108

  TODO for future

  - Auto-generate navbar config section when creating/saving new templates (currently needs manual addition to site.config.js)

  Test plan

  - Build passes
  - Verify navbar renders correctly with custom config
  - Verify navbar works without config (uses defaults)

**Purpose of this pull request:** Description

**(optional) Issues fixed**: fixes #<issue number>, fixes #<issue number>

## IMPORTANT - UI CHANGE DEMONSTRATION

If making a change that changes the existing UI, or adds/changes new UI elements like components, themes, or templates, you MUST include screenshots or demos/recordings of your changes:

Screenshots:

Site preview link:

## Other things worth discussing regarding PR:

Anything not covered by previous sections

### CODE REVIEW

File: src/lib/components/NavigationBar.svelte [hunk 1]
```diff
@@ -7,6 +7,24 @@
...
+
+  // Default navigation items (Home, About, etc.)
+  // Set to empty array to hide all default links
+  export let defaultNavItems = [
+    { title: 'Home', url: '/' },
+    { title: 'About', url: '/about' }
+  ];
+
+  // CTA Button configuration
+  export let ctaButton = {
```
Comment (fredxfred) [inline src/lib/components/NavigationBar.svelte]: why does this need to be hardcoded? why can it not be defaultNavItems? Are the values hardcoded?

Comment (semihpolat) [reply src/lib/components/NavigationBar.svelte]: it's updated now the user can choose which button will be the CTA or even have no CTA at all, directly from site.config.js

**Comment by semihpolat** [comment]
> let's wait to review/fix/move forward with this until the developer template pr is merged. @semihpolat please let me know when that happens

The Navbar changes made in this branch have been aligned with the developer-portfolio on the branch from PR #125

File: src/lib/components/NavigationBar.svelte [hunk 2]
```diff
@@ -7,7 +7,24 @@
...
   export let searchPlaceholder = "Search...";
-  
+
+  // Customizable site branding
+  export let siteTitle = null;
+  export let logo = null; // Can be image URL string or null for default SVG
+
+  // Default navigation items (Home, About, etc.)
+  // Set to empty array to hide all default links
+  export let defaultNavItems = [
```
Comment (fredxfred) [inline src/lib/components/NavigationBar.svelte]: why are we setting these in both the .svelte file default and in the site.config.js defaults?

Comment (semihpolat) [reply src/lib/components/NavigationBar.svelte]: We only set the real defaults in site.config.js. The component prop defaults are just fallbacks so the component can work independently if it’s ever used outside the config flow

Comment (fredxfred) [reply src/lib/components/NavigationBar.svelte]: I think the default for the component in independent use should be to only include the Home / url since it's not guaranteed that the user will have an about page.

I'm still not sure it makes sense for these to all be configurable in the site.config.js if they can just be configured as normal prop values in routes/+layout.svelte. We can leave it for now though
